version: '3.7'

services:
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    volumes:
      - ./data/db:/var/opt/mssql/data
    restart: always
  adlib-backend:
    image: adlib-backend
    restart: always
    volumes: 
      - './config/adlib2eventstream/config.tml:/usr/src/app/src/config.tml'
  eventstream:
    image: eventstream
    restart: always
    volumes: 
      - './config/adlib2eventstream/config.tml:/usr/src/app/src/config.tml'